### PR TITLE
feat(colors): Add more colors

### PR DESCRIPTION
**Pull request by jzeuzs**
Added:
 - opal
 - ruby
 - sapphire
 - jade
 - lapis-lazuli
 - bing
 - bitbucket
 - dogehouse
 - firefox
 - heroku
 - messenger
 - nodejs
 - replit
 - yarn

### CODE REVIEW

**Comment by jzeuzs** [comment]
@AlexFlipnote why

**Comment by jzeuzs** [comment]
@AlexFlipnote y u close this

**Comment by AlexFlipnote** [comment]
Because if you want more colours, make your own custom CSS for that. I will only have a few pre-made colours. In the next major update I will remove colours overall to reduce size.

**Comment by jzeuzs** [comment]
Oh okay 😀

**Pull request closed without merging**
