### PR TITLE
Navigation Bar

### PR DESCRIPTION
**Pull request by Snazzah**
preview

The navigation bar can be fixed and auto-collapses on resize.

Adds:
- Navigation bar

Changes:
- Moved the script tag to the bottom of the page to avoid page breaks
- Changed docs to use navigation bars
- Made `check_arrow` and `check_nav_bar` to be called on script initialization

### CODE REVIEW

**Comment by AlexFlipnote** [comment]
I would rather have a navbar that is both clickable and comes from the left side, something similar to this (aka. app menus)

Image

**Comment by Snazzah** [comment]
I could probably add that in as something like a "expandable sidebar". Would it be OK to add that in as a new thing or to replace nav-bars with that?

**Comment by AlexFlipnote** [comment]
Preferably replace.

**Comment by Snazzah** [comment]
Should the header also move with the rest of the page or stay?

**Comment by AlexFlipnote** [comment]
eh maybe don't move the page, kinda overkill now that I rethink it.
Just make the menu get dragged out like usual Android menus.

**Comment by Snazzah** [comment]
Redesigned it.

###### Normal Preview
preview

###### Fixed Preview
preview

**Pull request merged**
