### PR TITLE
Added twitch color

### PR DESCRIPTION
**Pull request by Cyber28**
The css compressor I used fucked up css/colours.min.css

### CODE REVIEW

**Comment by AlexFlipnote** [comment]
I do not write directly into the CSS file.. use SCSS

**Comment by Cyber28** [comment]
Done i think

**Comment by AlexFlipnote** [comment]
I can make a new commit about it, will close it and do it.

**Comment by AlexFlipnote** [comment]
Added now in 2e90b2f

**Comment by Cyber28** [comment]
Thank you! ^^

**Pull request closed without merging**
